// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHSOS.Data;

#nullable disable

namespace SHSOS.Migrations
{
    [DbContext(typeof(SHSOSDbContext))]
    [Migration("20260116064629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SHSOS.Models.Departments", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("HospitalID")
                        .HasColumnType("int");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentID");

                    b.HasIndex("HospitalID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.EnergyConsumption", b =>
                {
                    b.Property<int>("EnergyConsumptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnergyConsumptionID"));

                    b.Property<decimal>("CarbonEmissionsKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("MeterReadingStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PeakHourFlag")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ReadingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitsConsumedkWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsageCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnergyConsumptionID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("EnergyConsumption");
                });

            modelBuilder.Entity("SHSOS.Models.WasteManagement", b =>
                {
                    b.Property<int>("WasteRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WasteRecordID"));

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComplianceStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("DisinfectionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DisposalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisposalMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SegregationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WasteWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WasteRecordID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("WasteManagement");
                });

            modelBuilder.Entity("SHSOS.Models.WaterConsumption", b =>
                {
                    b.Property<int>("ConsumptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumptionID"));

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("LeakageDetected")
                        .HasColumnType("bit");

                    b.Property<decimal>("ReadingEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("ReadingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitsConsumedLiters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeatherCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsumptionID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("WaterConsumption");
                });

            modelBuilder.Entity("SHSOS.Models.hospitals", b =>
                {
                    b.Property<int>("HospitalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalID"));

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalID");

                    b.ToTable("hospitals");
                });

            modelBuilder.Entity("SHSOS.Models.Departments", b =>
                {
                    b.HasOne("SHSOS.Models.hospitals", "hospitals")
                        .WithMany("Departments")
                        .HasForeignKey("HospitalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospitals");
                });

            modelBuilder.Entity("SHSOS.Models.EnergyConsumption", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany("EnergyConsumption")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.WasteManagement", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany("WasteManagement")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.WaterConsumption", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany("WaterConsumption")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.Departments", b =>
                {
                    b.Navigation("EnergyConsumption");

                    b.Navigation("WasteManagement");

                    b.Navigation("WaterConsumption");
                });

            modelBuilder.Entity("SHSOS.Models.hospitals", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
