// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHSOS.Data;

#nullable disable

namespace SHSOS.Migrations
{
    [DbContext(typeof(SHSOSDbContext))]
    partial class SHSOSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("snot")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SHSOS.Models.Alert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertID"));

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AlertID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Alert", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditLogID");

                    b.ToTable("AuditLogs", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.Departments", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("HospitalID")
                        .HasColumnType("int");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentID");

                    b.HasIndex("HospitalID");

                    b.ToTable("Departments", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.EnergyConsumption", b =>
                {
                    b.Property<int>("EnergyConsumptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnergyConsumptionID"));

                    b.Property<decimal>("CarbonEmissionsKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("MeterReadingStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PeakHourFlag")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ReadingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitsConsumedkWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsageCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnergyConsumptionID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("EnergyConsumption", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.ResourceThreshold", b =>
                {
                    b.Property<int>("ThresholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThresholdID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CriticalThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThresholdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WarningThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ThresholdID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("ResourceThreshold", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.SustainabilityMetrics", b =>
                {
                    b.Property<int>("MetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricID"));

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CarbonReductionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ComplianceViolations")
                        .HasColumnType("int");

                    b.Property<decimal>("CostSavingsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("EnergyEfficiencyScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyPerBed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotentialSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SustainabilityScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCarbonEmissionKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WasteManagementScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WastePerBed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterEfficiencyScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterPerBed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MetricID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("SustainabilityMetrics", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.WasteManagement", b =>
                {
                    b.Property<int>("WasteRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WasteRecordID"));

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComplianceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("DisinfectionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DisposalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisposalMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SegregationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WasteWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WasteRecordID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("WasteManagement", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.WaterConsumption", b =>
                {
                    b.Property<int>("ConsumptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumptionID"));

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("LeakageDetected")
                        .HasColumnType("bit");

                    b.Property<decimal>("ReadingEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("ReadingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitsConsumedLiters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeatherCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeatherCondition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsumptionID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("WaterConsumption", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.hospitals", b =>
                {
                    b.Property<int>("HospitalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalID"));

                    b.Property<string>("HospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalID");

                    b.ToTable("hospitals", "snot");
                });

            modelBuilder.Entity("SHSOS.Models.Alert", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.Departments", b =>
                {
                    b.HasOne("SHSOS.Models.hospitals", "hospitals")
                        .WithMany("Departments")
                        .HasForeignKey("HospitalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospitals");
                });

            modelBuilder.Entity("SHSOS.Models.EnergyConsumption", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany("EnergyConsumption")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.ResourceThreshold", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.SustainabilityMetrics", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.WasteManagement", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany("WasteManagement")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.WaterConsumption", b =>
                {
                    b.HasOne("SHSOS.Models.Departments", "Departments")
                        .WithMany("WaterConsumption")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SHSOS.Models.Departments", b =>
                {
                    b.Navigation("EnergyConsumption");

                    b.Navigation("WasteManagement");

                    b.Navigation("WaterConsumption");
                });

            modelBuilder.Entity("SHSOS.Models.hospitals", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
